### PR TITLE
Retrieve data correctly in a forked process

### PR DESCRIPTION
**Pull request by hirose31**
The file handler (`\*{PACKAGE::DATA}`) points same address among a parent and child processes, so sometimes a child process fails to get data in following condition:

```
<child1>     <child2>
seek $d,0,0
             seek $d,0,0
<$d>
             <$d> # fail. position of $d is at end of file.
```

So explicitly open a target file and use this filehandle instead of `\*{PACKAGE::DATA}`.

### CODE REVIEW

**Comment by syohex** [comment]
This change broke `Amon2::Lite`(and maybe broke similar modules).

`Amon2::Lite` reads `__DATA__` section of `.psgi` file by
`Data::Section::Simple->new(caller(0))->get_data_section()`.

https://github.com/tokuhirom/Amon2-Lite/blob/master/lib/Amon2/Lite.pm#L159

`caller(0)` is `Plack::Sandbox::*` package when web application is launched by `plackup`
(or `Plack::Runner`). But `Plack::Sandbox::*` package  is not related to any file so
`$INC{"Plack::Sandbox::*"}` is `undef` and `__DATA__` section is not read.

https://github.com/miyagawa/Data-Section-Simple/blob/master/lib/Data/Section/Simple.pm#L33

`Amon2::Lite` test log with `Data::Section::Simple` 0.05 and 0.06 is [here](https://gist.github.com/syohex/10965821)

Tests are passed if `Plack::Sandbox::*` package is related to the file(by applying following patch
to `Plack::Util`), however I don't know it is correct.

``` diff
diff --git a/lib/Plack/Util.pm b/lib/Plack/Util.pm
index 6a3b5d0..68f15d6 100644
--- a/lib/Plack/Util.pm
+++ b/lib/Plack/Util.pm
@@ -114,6 +114,7 @@ sub _load_sandbox {
     local $0 = $_file; # so FindBin etc. works
     local @ARGV = ();  # Some frameworks might try to parse @ARGV

+    $INC{"Plack/Sandbox/$_package.pm"} = $_file;
     return eval sprintf <<'END_EVAL', $_package;
 package Plack::Sandbox::%s;
 {
```

Cc: @tokuhirom

**Comment by miyagawa** [comment]
Yeah that patch looks ugly, and i'm happy to revert the change and accept a patch that redo the fork safe behavior as optional.

**Comment by miyagawa** [comment]
How about making some lock around seek and read?

**Comment by hirose31** [comment]
Following patch is to seek and read exclusively using flock. 

This code has 2 considerations.
1. should retry using `LOCK_EX | LOCK_NB` instead of blocking `LOCK_EX`?
2. lock file remains

Do you have any advise or another patch?

``` diff
diff --git a/lib/Data/Section/Simple.pm b/lib/Data/Section/Simple.pm
index ab43ab4..0ef7019 100644
--- a/lib/Data/Section/Simple.pm
+++ b/lib/Data/Section/Simple.pm
@@ -7,6 +7,9 @@ package Data::Section::Simple;
 use base qw(Exporter);
 our @EXPORT_OK = qw(get_data_section);

+use File::Spec;
+use Fcntl qw(:flock);
+
 sub new {
     my($class, $pkg) = @_;
     bless { package => $pkg || caller }, $class;
@@ -23,8 +26,16 @@ sub get_data_section {
         my $d = do { no strict 'refs'; \*{$self->{package}."::DATA"} };
         return unless defined fileno $d;

+        my $lock_file = File::Spec->catfile(File::Spec->tmpdir, 'dss-'.$self->{package});
+        open my $lock_fh, '+>>', $lock_file or return;
+        flock $lock_fh, LOCK_EX; # FIXME LOCK_NB and should retry sometimes?
+
         seek $d, 0, 0;
         my $content = join '', <$d>;
+
+        close $lock_fh; # unlock
+        # FIXME how unlink $lock_file?
+
         $content =~ s/^.*\n__DATA__\n/\n/s; # for win32
         $content =~ s/\n__END__\n.*$/\n/s;

```

**Comment by hirose31** [comment]
ah... That patch cannot run correctly in multiple processes environment by different user, because cannot write to lock file.

If we can add PID of parent process into lock file path (`tmpdir/PPID-dss-PACKAGE`), can resolve that problem except setuid another user in child process...

hmmmm

**Comment by miyagawa** [comment]
Yeah that looks a little complicated. @tokuhirom what do you think?

**Comment by tokuhirom** [comment]
I have no idea to resolve @hirose31's issue correctly.
I suggest to fork DSS to D::S::S::ForkSafe or something.

**Comment by miyagawa** [comment]
But what if Data::Section::Simple is used inside a framework (like Amon2) and you want to use it in a forking server such as Starman?

**Comment by kazuho** [comment]
Should DSS be fork-safe?  It is impossible to serialize concurrent operation by more than one process against a single open file description (and aside from `@INC`, there would be other problems if we try to reopen the file, e.g. permissions after setuid, files being removed, ...).  OTOH it is easy for applications using DSS to serialize the access by using some kind of locking mechanism.

**Comment by syohex** [comment]
@miyagawa Could you upload reverted version to CPAN until this issue is resolved ?

**Comment by hirose31** [comment]
OK, I will use DSS 0.07 with serialization by flock or creating a wrapper class which read whole data in parent process (at load time) in my application.

Thanks :D

**Pull request merged**
